export const TOGGLE_STOCK_VIEW = 'TOGGLE_STOCK_VIEW';
export const CHANGE_REPORT = 'CHANGE_REPORT';
export const CHANGE_STATISTICS = 'CHANGE_STATISTICS';
export const CHANGE_PARTTERNS = 'CHANGE_PARTTERNS';